### DISCUSSION TITLE
Gitlab CI for library project

### DISCUSSION THREAD

**Discussion by theliuk** [mia-platform/community#134] [Q&A] [answered]
Hi,
I created a new nodejs project for a library.

I used this gitlab CI, which is based on the platform's pipeline templates

```
include:
  - file: "/build/node/template-node-npm.yml"
    project: "platform/pipelines-templates"
    ref: "master"
  - file: "/build/node/template-node-npm-test-latest.yml"
    project: "platform/pipelines-templates"
    ref: "master"

default:
  image: node:16.18.1-alpine

variables:
  IMAGE_NAME: project/mylibrary

```

The pipeline breaks at the build stage with the following error:

```
$ docker build --build-arg COMMIT_SHA=${CI_COMMIT_SHA} ${CUSTOM_BUILD_ARGS} --pull -t ${REMOTE_IMAGE_NAME}:${DOCKER_TAG} ${DOCKER_PATH}
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /builds/clients/project/group/libraries/mylibrary/Dockerfile: no such file or directory
```

It seems to me that the pipeline is looking for a `Dockerfile` inside the repository, but being a library, it has no Dockerfile.

Here there's a wiki [link](https://makeitapp.atlassian.net/wiki/spaces/NEN/pages/3761635481/Gestione+di+librerie+npm+interne) with some instructions for publishing a library on the corporate registry, but I was wondering whether I should use the platform pipeline templates or not.

Thanks,

Luca

**Comment by davidebianchi** [comment, marked as answer]
Hi @theliuk! There is a pipeline called: `template-library-node-npm.yml` (and also `template-library-node-npm-test-latest.yml`), you can try to use this. If you use yarn, there is also a version for yarn.

So, you can do something like:

```yaml
include:
  - file: "/build/node/template-library-node-npm.yml"
    project: "platform/pipelines-templates"
    ref: "master"
  - file: "/build/node/template-library-node-npm-test-latest.yml"
    project: "platform/pipelines-templates"
    ref: "master"

default:
  image: node:16.18.1-alpine

variables:
  IMAGE_NAME: project/mylibrary

```

**Reply by theliuk** [reply]
Hi @davidebianchi , thank you.
Is there any example of library project that uses those pipelines?

**Reply by theliuk** [reply]
I tried, 
I get this error from Gitlab:

<img width="551" alt="Schermata 2022-12-13 alle 17 47 21" src="https://user-images.githubusercontent.com/809858/207393654-19057ba0-3948-4ead-8b22-f07fef2fc1d3.png">

I'm sure it's a valid yaml

**Reply by davidebianchi** [reply]
Yes, this could be an issue with the pipeline. Can you try it now?

**Reply by theliuk** [reply]
Hi @davidebianchi , sorry for the late reply.
Seems to work now.

**Reply by theliuk** [reply]
Pipeline works but the build stage is absent even after tagging. Any idea?

Thanks

**Reply by davidebianchi** [reply]
The build stage? What do you want to build, is it JavaScript or typescript? In the pipeline it should not have the publish template, can you add you a step.

**Reply by theliuk** [reply]
Hi @davidebianchi , yeah, I meant the publish stage. It's a Node.js library. 
So, the publish stage isn't included in the platform template's pipeline?

**Reply by theliuk** [reply]
I found out this [wiki page](https://makeitapp.atlassian.net/wiki/spaces/NEN/pages/3761635481/Gestione+di+librerie+npm+interne) with a gitlab CI which has the `package` stage. I guess that's it to be added ad the end of my pipeline, after I include platform pipeline templates.

**Reply by davidebianchi** [reply]
The link is private, but yes it is possible to add a step to release the package.
For Gitlab CI, something like:

```yaml
publish:
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  script:
    - some command to login to npm
    - npm publish
```

**Reply by theliuk** [reply]
Why isn't it in the platform templates? After all, all our node.js packages go to the same registry (our nexus).

**Reply by frengooo** [reply]
Hi guys,
I added the same stage on my pipeline but it doesn't work, can you help me?

This is the pipeline:
```yml
publish-latest:
  stage: package

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: $CI_COMMIT_TAG

  script:
    - echo "${PRIVATE_NPM_REGISTRY_TOKEN}" > ${HOME}/.npmrc
    - npm publish

publish-tag:
  stage: package

  rules:
    - if: $CI_COMMIT_TAG

  script:
    - echo "${PRIVATE_NPM_REGISTRY_TOKEN}" > ${HOME}/.npmrc
    - npm publish
```

And this is the error I just got:
<img width="625" alt="Screenshot 2023-01-12 alle 11 33 48" src="https://user-images.githubusercontent.com/28152586/212044467-95276298-e355-4e18-80d3-e4338d16859e.png">
