### DISCUSSION TITLE
Traefik redirectRegex Middleware not working

### DISCUSSION THREAD

**Discussion by theliuk** [mia-platform/community#156] [Q&A] [answered]
I need to redirect all incoming request to a different server.ù
I followed [this doc by Traefik](https://doc.traefik.io/traefik/middlewares/http/redirectregex/), and this are my configurations:

**IngressRoute**
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mia-preprod-ingress
  labels:
    app.kubernetes.io/instance: "ingress-controller"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dev-portal-b2b.preprod.ec10278.gcp.mia-platform.eu`)
      middlewares:
        - name: mia-preprod-redirect
        - name: "ingress-controller-hsts-headers"
          namespace: mia-platform
      kind: Rule
      services:
        - name: api-gateway
          port: 8080
```

**Middleware**
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mia-preprod-redirect
spec:
  redirectRegex:
    regex: ^.*
    replacement: https://documentazione.it
    permanent: false
```

When I try to contact `dev-portal-b2b.preprod.ec10278.gcp.mia-platform.eu` I get Traefik standard `404 Not Found`.

**Comment by davidebianchi** [comment, marked as answer]
Hi @theliuk!

In the middleware, it misses the ingress labels. It is required to be read by Traefik.

So, you can change the middleware in this way:

```

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mia-preprod-redirect
  labels:
    app.kubernetes.io/instance: "ingress-controller"
spec:
  redirectRegex:
    regex: ^.*
    replacement: https://documentazione.it
    permanent: false
```
