### DISCUSSION TITLE
GitLab pipeline keeps failing using fake Google Storage Cloud image

### DISCUSSION THREAD

**Discussion by SalvadorCali** [mia-platform/community#179] [Q&A] [answered]
Hi, everyone!
To make an integration test for one of our services we used the following fake Google Storage Cloud image: https://github.com/fsouza/fake-gcs-server

The test creates a bucket and uploads two files inside it. 
We can run the tests locally with no issues, but the GitLab pipeline keeps failing.

This is the docker-compose we use locally:
```
version: '3.9'
services:
  kafka:
    image: nexus.mia-platform.eu/ci/kafka:1.0.1
    restart: always
    environment:
      ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092,INTERNAL://localhost:9093"
      LISTENERS: "PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093"
      SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
      INTER_BROKER: "INTERNAL"
    ports:
      - "2181:2181"
      - "443:9092"
      - "9092:9092"
      - "9093:9093"
  fake-gcs-server:
    image: fsouza/fake-gcs-server:1.44.0
    restart: always
    ports:
      - "4443:4443"
    command: ['-scheme', 'http']
```

This is the last part of the gitlab-ci file:
![image](https://user-images.githubusercontent.com/37811007/214100685-e94e5f87-8514-44f7-a1cd-6efcfb1d8f19.png)

We also tried to update the command part in this way:
```
command: ['-scheme', 'http', '-port', '80'] 
command: ['-scheme', 'http', '-port', '4443']
```
or set to the `GCS_API_ENDPOINT` variable the following value:
```
http://fake-gcs-server
```

This is the setup part of our test:
![image](https://user-images.githubusercontent.com/37811007/214100982-82d6a7f7-c6d8-47c5-83ca-8c1b6927aa4f.png)

And the following are the errors in the pipeline:
```
not ok 1 - request to http://[::]:4443/upload/storage/v1/b/test-bucket/o?uploadType=resumable&name=%2Fin%2Ftest-data.csv&upload_id=7c279e4e05de252e4eb03e684e619fc1 failed, reason: connect EADDRNOTAVAIL :::4443 - Local (:::0)
          --
        
        Bail out! request to http://[::]:4443/upload/storage/v1/b/test-bucket/o?uploadType=resumable&name=%2Fin%2Ftest-data.csv&upload_id=7c279e4e05de252e4eb03e684e619fc1 failed, reason: connect EADDRNOTAVAIL :::4443 - Local (:::0)
Bail out! request to http://[::]:4443/upload/storage/v1/b/test-bucket/o?uploadType=resumable&name=%2Fin%2Ftest-data.csv&upload_id=7c279e4e05de252e4eb03e684e619fc1 failed, reason: connect EADDRNOTAVAIL :::4443 - Local (:::0)
```
```
 not ok 1 - request to http://fake-gcs-server/storage/v1/b?project=test failed, reason: connect ECONNREFUSED 172.17.0.3:80
Bail out! request to http://fake-gcs-server/storage/v1/b?project=test failed, reason: connect ECONNREFUSED 172.17.0.3:80
Bail out! request to http://fake-gcs-server/storage/v1/b?project=test failed, reason: connect ECONNREFUSED 172.17.0.3:80
```

Do you have any advices?
