### DISCUSSION TITLE
[Headless CMS] Export not working for wrong v1-adapter export service URL

### DISCUSSION THREAD

**Discussion by frengooo** [mia-platform/community#261] [Q&A] [answered]
### Which section?

Console

### Which is the version?

v11.0.2

### Description

Hi guys,
I'm trying to use the `export-service` to export data from the Headless CMS.

I created the `export-service` on the Mia-Platform Console directly from the marketplace but, when I try to export data through the Headless CMS, it doesn't work.

The problem is that the `/exports` request is handled by the `v1-adapter`.
The `v1-adapter` has the `EXPORT_SERVICE_URL` environment variable set to `http://undefined/export` by default and I am not able to change it.

I tried to:
- editing the value inside the `v1-adapter.deployment.yml` file &rarr; overwritten by the console;
- adding the right variable inside the `api-console-config.json` file &rarr; removed by the console.

How can I fix it?
Following you can find the error log:
```json
{
  ...
  "err": {
    "type": "",
    "message": "getaddrinfo ENOTFOUND undefined",
    ...
    "url": "http://undefined/export",
  }
}
```

**Comment by fredmaggiowski** [comment, marked as answer]
Hi, have you added the `export-service` within the project `enabledServices` field?

**Reply by frengooo** [reply]
Hi @fredmaggiowski, no, I manually added it through the "Microservices" section on the "Design" area.

**Reply by frengooo** [reply]
@fredmaggiowski I manually temporarily updated the variable to the right one and it worked. The client prefers to keep the `export-service` in the microservices section to have more control over it.

Is there a way to update the `EXPORT_SERVICE_URL` variable of the `v1-adapter` in addition to kustomize?

**Reply by frengooo** [reply]
@fredmaggiowski I did it using kustomize and it worked 💪 I created this patch file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-adapter
spec:
  template:
    spec:
      containers:
        - name: v1-adapter
          env:
            - name: EXPORT_SERVICE_URL
              value: http://export-service/export
```

Another question. Is it possible to apply a _patch_ for all environments or do I need to duplicate the file for all environments?
