### DISCUSSION TITLE
[Deploy] Container pull from custom registry

### DISCUSSION THREAD

**Discussion by frengooo** [mia-platform/community#274] [Q&A] [answered]
### Which section?

Console

### Which is the version?

v11

### Description

Hi guys,
we are working, for a PoC, to an `mlp` extension to customize the `.deploy-job` step used to deploy a project.

Is there a way to import the deploy tool (like `mlp`) from a private registry? e.g:
```yaml
...
  .docker-job:
    image: my-private-registry.com/my-deploy-cli
...
```

Do I need to add a pre-deploy job with the `docker login` command or is there an easier way?

Thanks.

**Comment by fredmaggiowski** [comment]
I think adding docker login is the way to go, is there something bothering you about it?

**Comment by davidebianchi** [comment, marked as answer]
Hi! Yes, you need to register to the registry where the image is located if it's private.
If you are using gitlab, you could see their docs: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#access-an-image-from-a-private-container-registry and ask to the administrator of your pipelines for more info.

**Reply by frengooo** [reply]
Hi @davidebianchi, we solved using the `DOCKER_AUTH_CONFIG` variable, thanks 😄
Following the configuration, if someone need it:
```yaml
DOCKER_AUTH_CONFIG: '{
      "auths": {
          "my-private-registry.com": {
              "auth": "ZWg6dm9sZWVlZWV2aQo="
          }
      }
    }'
```
