### DISCUSSION TITLE
[Environment][Deploy] Unable to deploy new environment, missing namespace

### DISCUSSION THREAD

**Discussion by frengooo** [mia-platform/community#278] [Q&A] [answered]
### Which section?

Console

### Which is the version?

v11

### Description

Hi guys,
I successfully created a new environment on a project and the related namespace was correctly created.

After that, following the [public documentation](https://docs.mia-platform.eu/docs/development_suite/set-up-infrastructure/add-environment#enable-the-pipeline), I updated the `.gitlab-ci` file and the `overlays` folder (it's a Kustomize project).

This environment has a dedicated cluster, different from the default one.
The deploy pipeline is failing because it can't find the `training-productiondr` namespace, but I verified that it exists, on the right cluster:
![Screenshot 2023-06-22 at 14 21 27](https://github.com/mia-platform/community/assets/28152586/05267658-e8eb-4eb0-a158-8bbb54a37592)

I think the pipeline is trying to deploy on the wrong cluster, that doesn't have the `training-productiondr` namespace.
Following the `.gitlab-ci` of the environment:
```yaml
PRODUCTIONDR:
  stage: release
  extends: .deploy_job

  variables:
    ENVIRONMENT_PREFIX: "PRODUCTIONDR_"
    KUBE_URL: "${KUBE_URL_DR}"
    KUBE_CA_PEM: "${KUBE_CA_PEM_DR}"
    KUBE_TOKEN: "${KUBE_TOKEN_DR}"
  
  after_script:
    - echo $KUBE_URL

  only:
    variables:
      - $ENVIRONMENT_TO_DEPLOY == "PRODUCTIONDR"
```

and the environment configuration on the console:
![Screenshot 2023-06-22 at 14 25 31](https://github.com/mia-platform/community/assets/28152586/4df3f713-e083-464b-a457-de8953b794cc)

I created the `KUBE_*` variables above at the company level (I tried at the project level too but it doesn't work).
What am I doing wrong?

### Actual Outcome

The pipeline fails.

### Expected Outcome

The pipeline doesn't fail.

**Comment by davidebianchi** [comment, marked as answer]
Hi!
The pipeline configured in this way does not create the namespace (there is the `--ensure-namespace` flag of mlp set to false). If the namespace does not exists, it fails.
When you create a new environment from Console, it should also create the namespace in the cluster (if the service account of the token used by Console has the permissions to create new namespaces). You can [see here](https://docs.mia-platform.eu/docs/development_suite/clusters-management/clusters-overview-setup#cluster-preparation) the suggested permissions (when environment is created, you should be notified if namespace creation is not successfull).
Otherwise, you should manage the namespace creation in another way (add the permissions, or manually create it, or manage with some other automation).

**Reply by frengooo** [reply]
Hi @davidebianchi,
the namespace was created when I created the environment on the console.
I can see the namespace on the cluster, for this reason I don't understand the error.

**Reply by davidebianchi** [reply]
Are the env var of the kubernetes context correctly set, and the service account of the pipeline has the permission to create resources in it?

**Reply by frengooo** [reply]
The service account has the permissions (I tried in another way and it worked).
The env var are correct and I added them at client group level.

**Reply by frengooo** [reply]
Thanks to @davidebianchi we found the problem.

For this client we have two clusters and the `KUBE_*` environment variables was the following:

* Primary cluster:
   * KUBE_URL
   * KUBE_CA_PEM
   * KUBE_TOKEN

* Secondary cluster:
   * KUBE_URL_DR
   * KUBE_CA_PEM_DR
   * KUBE_TOKEN_DR

Deploying on the second cluster, we overwrote the KUBE_URL, KUBE_CA_PEM and KUBE_TOKEN variables on the gitlab-ci file, as you can see in the screenshot above.
Despite that, the job `.deploy-job` didn't use the overwrote KUBE_URL, KUBE_CA_PEM and KUBE_TOKEN, but the original ones defined in the Gitlab environment variables because of the same name.

We solved renaming the environment variables of the primary cluster in:
* KUBE_URL_PRIMARY
* KUBE_CA_PEM_PRIMARY
* KUBE_TOKEN_PRIMARY

Now the ci file is:
```yaml
PRODUCTION:
  stage: release
  extends: .deploy_job

  variables:
    ENVIRONMENT_PREFIX: "PRODUCTION_"
    KUBE_URL: "${KUBE_URL_PRIMARY}"
    KUBE_CA_PEM: "${KUBE_CA_PEM_PRIMARY}"
    KUBE_TOKEN: "${KUBE_TOKEN_PRIMARY}"

  only:
    variables:
      - $ENVIRONMENT_TO_DEPLOY == "PRODUCTION"

PRODUCTIONDR:
  stage: release
  extends: .deploy_job

  variables:
    ENVIRONMENT_PREFIX: "PRODUCTIONDR_"
    KUBE_URL: "${KUBE_URL_DR}"
    KUBE_CA_PEM: "${KUBE_CA_PEM_DR}"
    KUBE_TOKEN: "${KUBE_TOKEN_DR}"

  only:
    variables:
      - $ENVIRONMENT_TO_DEPLOY == "PRODUCTIONDR"
```
