### DISCUSSION TITLE
Fast Data - No Projection changes

### DISCUSSION THREAD

**Discussion by SalvadorCali** [mia-platform/community#28] [Q&A] [answered]
Hi, everyone!
We setup the Real-Time Updater and the Single View Creator Low Code and we correctly generate projections from Kafka messages, but there are no projection changes on MongoDB and Kafka.
Real-Time Updater environment variables:
```
env:
            - name: LOG_LEVEL
              value: '{{LOG_LEVEL}}'
            - name: MICROSERVICE_GATEWAY_SERVICE_NAME
              value: microservice-gateway
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: HTTP_PORT
              value: '3000'
            - name: USERID_HEADER_KEY
              value: miauserid
            - name: GROUPS_HEADER_KEY
              value: miausergroups
            - name: CLIENTTYPE_HEADER_KEY
              value: client-type
            - name: BACKOFFICE_HEADER_KEY
              value: isbackoffice
            - name: USER_PROPERTIES_HEADER_KEY
              value: miauserproperties
            - name: KAFKA_USE_LATEST_DEQUEUE_STRATEGY
              value: 'false'
            - name: PROJECTIONS_DATABASE_NAME
              value: '{{FAST_DATA_PROJECTIONS_DATABASE_NAME}}'
            - name: PROJECTIONS_CHANGES_ENABLED
              value: 'true'
            - name: LC39_HTTP_PORT
              value: '3000'
            - name: LIVENESS_INTERVAL_MS
              value: '100'
            - name: STRATEGIES_MAX_EXEC_TIME_MS
              value: '10000'
            - name: KAFKA_BROKERS
              value: '{{KAFKA_BROKERS}}'
            - name: MONGODB_URL
              value: '{{PROJECTIONS_MONGODB_URL}}'
            - name: CAST_FUNCTIONS_FOLDER
              value: /home/node/app/configurations/castFunctionsFolder
            - name: MAP_TABLE_FOLDER
              value: /home/node/app/configurations/mapTableFolder
            - name: STRATEGIES_FOLDER
              value: /home/node/app/configurations/strategies
            - name: PROJECTIONS_CHANGES_COLLECTION_NAME
              value: '{{FAST_DATA_PROJECTIONS_CHANGES_COLLECTION_NAME}}'
            - name: INVARIANT_TOPIC_MAP
              value: '{{FAST_DATA_INVARIANT_TOPIC_MAP_UCMDB}}'
            - name: KAFKA_GROUP_ID
              value: '{{FAST_DATA_KAFKA_GROUP_ID_UCMDB}}'
            - name: KAFKA_SASL_USERNAME
              value: '{{KAFKA_SASL_USERNAME}}'
            - name: KAFKA_SASL_PASSWORD
              value: '{{KAFKA_SASL_PASSWORD}}'
            - name: KAFKA_MESSAGE_ADAPTER
              value: custom
            - name: KAFKA_ADAPTER_FOLDER
              value: /home/node/app/configurations/kafkaAdapterFolder
            - name: FORCE_CHECK_ON_OFFSET
              value: 'true'
            - name: COMMIT_MESSAGE_LOGGING_INTERVAL
              value: '0'
            - name: USE_AUTOMATIC_STRATEGIES
              value: 'true'
            - name: ER_SCHEMA_FOLDER
              value: /home/node/app/erSchema
            - name: PROJECTION_CHANGES_SCHEMA_FOLDER
              value: /home/node/app/projectionChangesSchema
```

Single View Creator environment variables:
```
env:
            - name: LOG_LEVEL
              value: '{{LOG_LEVEL}}'
            - name: CONFIGURATION_FOLDER
              value: /home/node/app/configuration
            - name: MICROSERVICE_GATEWAY_SERVICE_NAME
              value: microservice-gateway
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: HTTP_PORT
              value: '3000'
            - name: USERID_HEADER_KEY
              value: miauserid
            - name: GROUPS_HEADER_KEY
              value: miausergroups
            - name: CLIENTTYPE_HEADER_KEY
              value: client-type
            - name: BACKOFFICE_HEADER_KEY
              value: isbackoffice
            - name: USER_PROPERTIES_HEADER_KEY
              value: miauserproperties
            - name: TYPE
              value: nodes
            - name: SCHEDULING_TIME
              value: '100'
            - name: PROJECTIONS_MONGODB_URL
              value: '{{PROJECTIONS_MONGODB_URL}}'
            - name: SINGLE_VIEWS_MONGODB_URL
              value: '{{SINGLE_VIEWS_MONGODB_URL}}'
            - name: PROJECTIONS_DATABASE
              value: '{{FAST_DATA_PROJECTIONS_DATABASE_NAME}}'
            - name: PROJECTIONS_CHANGES_DATABASE
              value: '{{FAST_DATA_PROJECTIONS_DATABASE_NAME}}'
            - name: PROJECTIONS_CHANGES_COLLECTION
              value: '{{FAST_DATA_PROJECTIONS_CHANGES_COLLECTION_NAME}}'
            - name: SINGLE_VIEWS_DATABASE
              value: '{{FAST_DATA_PROJECTIONS_DATABASE_NAME}}'
            - name: SINGLE_VIEWS_COLLECTION
              value: nodes
            - name: SINGLE_VIEWS_ERRORS_COLLECTION
              value: single_views_errors
            - name: SINGLE_VIEWS_PORTFOLIO_ORIGIN
              value: ucmdb
            - name: KAFKA_CLIENT_ID
              value: ucmdb-svc-nodes-{{TOPIC_ENV}}
            - name: KAFKA_BROKERS_LIST
              value: '{{KAFKA_BROKERS}}'
            - name: SEND_BA_TO_KAFKA
              value: 'false'
            - name: KAFKA_SASL_USERNAME
              value: '{{KAFKA_SASL_USERNAME}}'
            - name: KAFKA_SASL_PASSWORD
              value: '{{KAFKA_SASL_PASSWORD}}'
            - name: KAFKA_SASL_MECHANISM
              value: plain
            - name: USE_AUTOMATIC
              value: 'true'
            - name: AGGREGATION_FOLDER
              value: /home/node/app/aggregation
            - name: ER_SCHEMA_FOLDER
              value: /home/node/app/erSchema
```
Which could be the problem? Please tell me if you need other information (i.e. erSchema, projectionChangesSchema).
