### DISCUSSION TITLE
Would like to enable external proxies to use http 1.1

### DISCUSSION THREAD

**Discussion by phil-hotchkiss** [mia-platform/community#428] [Q&A] [answered]
### What product are you having troubles with?

Console

### What Console version are you using?

12.2.1

### Description

We are having trouble leveraging the external proxies at the moment because the VIPs that are being targeted are currently only configured to support HTTP/1.1 traffic. The envoyproxy configuration that is produced seems to coerce all traffic into communicating over HTTP/2. Is there a way to have Mia produce a cds.json that enables communication with targets that are configured for HTTP/1.1?

**Comment by davidebianchi** [comment, marked as answer]
Hi @phil-hotchkiss! At the moment, it should be possible changing the cluster configuration of the generated envoy configuration.
It is possible to modify the upstream connection configuration following [this documentation](https://docs.mia-platform.eu/docs/development_suite/api-console/advanced-section/api-gateway-envoy/extensions#clusters).

Something like this, changing the `service-name`, `your-address` and `the-port-number` with your service name, should work:

```yaml
'@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
name: service-name
connect_timeout: 30s
type: LOGICAL_DNS
lb_policy: ROUND_ROBIN
protocol_selection: USE_CONFIGURED_PROTOCOL
typed_extension_protocol_options:
  envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
    '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
    explicit_http_config:
      http_protocol_options: {}  <-- This configuration should explicitly target to http 1.1
load_assignment:
  cluster_name: service-name
  endpoints:
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: your-address
                port_value: the-port-number
```

The envoy reference docs is [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#cluster-configuration-proto).
