### DISCUSSION TITLE
Add K8S ServiceAccount in deployment file

### DISCUSSION THREAD

**Discussion by rafpor75** [mia-platform/community#544] [General]
### Description

What product are you having troubles with?
Microservice deployment configuration

What Mia-Platform Suite version are you using?
12.0.2

What Console version are you using?
1.93.1
Hi,
I need to add a K8S ServiceAccount into a deployment file of a service, ex:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-name
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::xxxyyyyzzzz:role/environment-service" 
```

I can add this feature manually editing the file into gitlab: service-name.deployment.yml, but each time I  deploy again the service after I modify it, I lost the configuration, such as the system recreate the file following a template model.

How can I solve?

this ServiceAccount isn't the Mia Platform "ServiceAccount" configurable by Mia Platform Console, it is a resource used by K8S

and it is defined in the deployment.yaml of the Service.

I have identified this advanced configuration, could you confirm and provide me more documentation  how to use this advanced feature?
![image](https://github.com/user-attachments/assets/4baeca76-36bd-42fd-8031-d0804912c2d2)

Thank you :)

**Comment by frengooo** [comment]
Hi @rafpor75,
thanks for reaching out.

As you already mentioned, the "Advanced Configuration" of course will allow you to specify an additional "Service Account" inside you service deployment file.
Despite that, the "Advanced Configuration" implies that you will always need to **manually create and update** the manifests (`deployment` and `service`) of your service and we usually discourage that, because it's very uncomfortable and error prone.

As alternative I propose you Kustomize, already integrated with the Console, to add your custom service account to the deployment.
In order to do that:
* be sure your project has Kustomize enabled and, if not, you can easily migrate it to Kustomize &rarr; https://docs.mia-platform.eu/docs/console/project-configuration/kustomize-your-configurations/migrate-to-kustomize
* create your `patch` to add the service account inside your specific deployment. You can find an example [here](https://docs.mia-platform.eu/docs/console/project-configuration/kustomize-your-configurations/migrate-to-kustomize).

The example above is about overriding the static replicas, but your use case is pretty similar, you just need to modify the example to set a different service account instead of the replicas, removing the "static replicas" part.

Let us know if this helps.

**Reply by rafpor75** [reply]
thank you very much for the prompt reply :)

I tried the second option without success. This involved adding a file named serviceaccount.patch.yaml to the /overlays/COLL directory. The content of the file was:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bff-idengine
spec:
    serviceAccountName: bff-idengine
    spec:
      annotations:
    eks.amazonaws.com/role-arn: ""arn:aws:iam::xxxyyyyzzzz:role/environment-service"`
    
I also modified the kustomization.yaml file located in configurations/overlays/COLL. The changes were:
    
    `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../configuration
patches:
- path: serviceaccount.patch.yaml
  target:
    kind: ServiceAccount
```

The bff-service was not deployed due to the following error:

```
reason: MinimumReplicasUnavailable

  status: "False"

  type: Available

- lastTransitionTime: "2024-09-03T10:13:10Z"

  lastUpdateTime: "2024-09-03T10:13:10Z"

  message: 'pods "bff-idengine-5c6658668b-" is forbidden: error looking up service

    account idengine-credit-agricole-cl/bff-idengine: serviceaccount "bff-idengine"

    not found'

  reason: FailedCreate

  status: "True"

  type: ReplicaFailure

observedGeneration: 98

unavailableReplicas: 1
```
