### DISCUSSION TITLE
Keycloak login issue

### DISCUSSION THREAD

**Discussion by rafpor75** [mia-platform/community#558] [General]
### Description

What product are you having troubles with?

authentication-service:3.7.0
login-site:8.1.2
authorization-service:2.4.2

What Console version are you using?
12

Description

Hi!

I configured all above services to use Keycloak.

when  I call my backoffice it redirects to 
`https://backoffice_url/authorize?state=493ceb54-1ced-4b0b-a21b-b9b3ea8590a9&redirect=%2Fbackoffice`
and I receive the below error:
**appId and providerId query params are required**

if I manually add the parameters `appId=web&providerId=keycloak` in the url
I have the error: the state param is not valid after login execution

this is the configuration of my authentication-service:

`{
  "apps": {
    "web": {
      "providers": {
        "keycloak": {
          "type": "keycloak",
          "clientId": "idbackoffice",
          "clientSecret": "blablablablablablablablablabla",
          "authUrl": "https://keycloak_url/auth/realms/myrealm/protocol/openid-connect/auth",
          "tokenUrl": "https://keycloak_url/auth/realms/myrealm/protocol/openid-connect/token",
          "userInfoUrl": "https://keycloak_url/auth/realms/myrealm/protocol/openid-connect/userinfo",
          "baseUrl": "https://keycloak_url/{tenantId}/auth/realms/myrealm/",
          "scope": [
            "openid"
          ],
          "order": 10,
          "userSettingsURL": "https://keycloak_url/dashboard"
        }
      },
      "authorizeStateRequired": false,
      "redirectUrl": "https://keycloak_url/auth/realms/myrealm/broker/keycloak/endpoint",
      "realm": "myrealm",
      "issuer": "https://keycloak_url/auth/realms/myrealm",
      "defaultGroups": []
    }
  }
}
`
Thank you

**Comment by GabrieleGuelfi** [comment]
Hello,
you can configure your api-gateway to add automatically the `appId` query param, to do so you should go to the Advanced section of the Console.
Here an example for envoy, that you should put in the `local-replies.yaml`, assuming that you have a listener called `frontend`:
```yaml
- listener_name: frontend
  filter:
    status_code_filter:
      comparison:
        op: EQ
        value:
          default_value: 401
          runtime_key: key_b
  status_code: 302
  body:
    inline_string: |-
      <html>
        <head>
          <meta http-equiv="content-type" content="text/html;charset=utf-8">
            <title>302 Found</title>
        </head>
      </html>
  headers_to_add:
  - header:
      key: "Location"
      value: "/web-login?appId=web&redirect=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
    append: false
```

For the nginx gateway you should look in `api-gateway -> server-extension.conf`.

Hope it helps!
