### DISCUSSION TITLE
What is the correct pipelinefor generating the SBOM for the React + TypeScript + Vite template

### DISCUSSION THREAD

**Discussion by alexBonadei** [mia-platform/community#588] [Q&A]
### What product are you having troubles with?

Marketplace

### What Console version are you using?

v13.5.0

### Description

Hi,

I have a frontend service created using the React Template. So far the pipeline was based from this:
```
include:
  - file: "/build/node/template-react-yarn.yml"
    project: "platform/pipelines-templates"
    ref: "master"

...
```

Now I'd like to generate also the SBOM of the service. I made an attempt using this one (that I'm using for the Backend Service):

```
include:
- project: platform/pipelines-templates
  file: Application.gitlab-ci.yml
  ref: HEAD
- template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

...
```

And it's not working.
Can anyone suggest me what is the correct pipeline.

Thank you in advance!

**Comment by Danielecina** [comment]
Hi @alexBonadei, Can you specify what problem you have? 
Can the cosign private key or GCP audience be missing?

For example:
```
sbom-and-sign-docker-image:
  variables:
    COSIGN_PRIVATE_KEY: '/path/to/cosign-key.pem'
  id_tokens:
    GCP_WORKLOAD_IDENTITY:
      aud: 'https://www.googleapis.com/authpath/cloud-platform'
```
