### DISCUSSION TITLE
[gitlab-CI] Unable to deploy branches after enabling CD

### DISCUSSION THREAD

**Discussion by frengooo** [mia-platform/community#80] [Q&A] [answered]
Hi guys,
I have a problem regarding the Gitlab CI of a `configurations` project.

By default the pipelines of configurations projects don't run when a user pushes a commit or creates a new tag.

A client asked us to enable CD in the following cases:
- if the environment is `INTEGRATION`
**and**
- if the commit is on the default branch **or** if a tag has been created

I added this rules to the `.gitlab-ci` file of the project:
```yaml
rules:
    - if: $CI_COMMIT_TAG
      variables:
        ENVIRONMENT_TO_DEPLOY: "INTEGRATION"
        DEPLOY_TYPE: "smart_deploy"
        FORCE_DEPLOY_WHEN_NO_SEMVER: "true"
        KUBE_NAMESPACE: "{{clientNamespace}}"
        STAGE_TO_DEPLOY: "INTEGRATION"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        ENVIRONMENT_TO_DEPLOY: "INTEGRATION"
        DEPLOY_TYPE: "smart_deploy"
        FORCE_DEPLOY_WHEN_NO_SEMVER: "true"
        KUBE_NAMESPACE: "{{clientNamespace}}"
        STAGE_TO_DEPLOY: "INTEGRATION"
```

Now if I commit on the default branch of push a tag the pipeline automatically starts, but I am not able to manually deploy other branches anymore, I just get a `Internal server error` from Gitlab.

I tried to add the following rule, but it doesn't work:
```yaml
    - if: $CI_PIPELINE_SOURCE == "web"
      when: "always"
```

Can you help me please?

**Comment by davidebianchi** [comment, marked as answer]
Hi @silversoul93! The last config is about web, that should be a trigger by the Gitlab UI.

In this case, what if you add as first entry:

```yaml
  - if: $ENVIRONMENT_TO_DEPLOY == "INTEGRATION"
    when: "always"
```
?

**Reply by frengooo** [reply]
Hi @davidebianchi, thanks for your help, it worked.
Just for information, I needed to add `if` statement for other environments too, otherwise the manual deploy didn't work for other environments. Following the "final" (I hope) version:
```yaml
workflow:
  rules:
    - if: $ENVIRONMENT_TO_DEPLOY == "INTEGRATION"
      when: "always"
    - if: $ENVIRONMENT_TO_DEPLOY == "STAGE"
      when: "always"
    - if: $ENVIRONMENT_TO_DEPLOY == "PROD"
      when: "always"
    - if: $CI_COMMIT_TAG
      variables:
        ENVIRONMENT_TO_DEPLOY: "INTEGRATION"
        DEPLOY_TYPE: "smart_deploy"
        FORCE_DEPLOY_WHEN_NO_SEMVER: "true"
        KUBE_NAMESPACE: "{{clientNamespace}}"
        STAGE_TO_DEPLOY: "INTEGRATION"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        ENVIRONMENT_TO_DEPLOY: "INTEGRATION"
        DEPLOY_TYPE: "smart_deploy"
        FORCE_DEPLOY_WHEN_NO_SEMVER: "true"
        KUBE_NAMESPACE: "{{clientNamespace}}"
        STAGE_TO_DEPLOY: "INTEGRATION"
```
