### DISCUSSION TITLE
cronjob activeDeadlineSeconds spec is not applied

### DISCUSSION THREAD

**Discussion by SimoneBergonzi** [mia-platform/community#83] [Q&A] [answered]
Hi guys,
as a fallback in case a cronjob does not end on its own, we tried to set the spec [activeDeadlineSeconds](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup).
This is part of the cronjob configuration:
```
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  activeDeadlineSeconds: 10800
  schedule: 0 2 * * *
  suspend: {{IMPORTER_SUSPENDED}}
  jobTemplate:
    spec:
      backoffLimit: 1
      completions: 1
      parallelism: 1
      template:
        metadata:
```

But it seems that this property is not applied to the cronjob 

```
Concurrency Policy:            Forbid
Suspend:                       False
Successful Job History Limit:  2
Failed Job History Limit:      2
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   1
Completions:                   1
```

Are we missing something?
